name: "On push changes"

on:
  push:
    branches-ignore:
      - main
      - master

# TODO make inputs from this
env:
  GO_VERSION: '1.20'
  MAIN_FILE: 'cmd/main.go'

permissions:
  contents: write

jobs:
  code-style:
    name: Code Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.RELEASE_KEY }}
      - uses: actions/setup-go@v4
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Go Module tidy
        run: go mod tidy
      - name: Run yaml linter
        id: yaml-lint
        uses: ibiqlik/action-yamllint@v3.1
        with:
          config_data: |
            extends: default
            ignore:
              - swagger.yaml
            rules:
              truthy:
                check-keys: false
              document-start:
                present: false
                level: warning
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: yamllint-logfile
          path: ${{ steps.yaml-lint.outputs.logfile }}

      - name: clean yaml-lint log
        if: always()
        run: rm ${{ steps.yaml-lint.outputs.logfile }}

      - name: "Commit & Push"
        id: commit
        if: always()
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update generated files"
          default_author: github_actions
