name: "Reuse me"

on:
  workflow_call:
    inputs:
      os:
        description: "OS"
        default: '["ubuntu-latest", "macos-latest"]'
        required: false
        type: string

jobs:
  build:
    strategy:
      matrix:
        os: ${{ fromJSON(inputs.os)}}
    runs-on: ${{ matrix.os }}
    steps:
      - name: "OS print"
        run: "uname"
